[phases.setup]
nixPkgs = ["maven", "openjdk17"]

[phases.install]
cmds = ["mvn clean install -DskipTests"]

[phases.build]
cmds = ["mvn package -DskipTests"]

[start]
cmd = "java -jar target/Conecta_Cusco-0.0.1-SNAPSHOT.jar" 