[build]
builder = "nixpacks"

[deploy]
startCommand = "java -jar target/Conecta_Cusco-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
SPRING_PROFILES_ACTIVE = "prod" 